# Generated by Django 2.0.7 on 2019-07-31 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.IntegerField(choices=[(0, '准备中'), (1, '进行中'), (2, '已结束'), (3, '已取消')], verbose_name='状态')),
                ('type', models.IntegerField(choices=[(0, '首页头图'), (1, '类型1'), (2, '类型2'), (3, '类型3'), (4, '类型4')], verbose_name='类型')),
                ('event_title', models.CharField(max_length=100, verbose_name='标题')),
                ('event_alt', models.TextField(blank=True, max_length=100, null=True, verbose_name='简述')),
                ('event_body', models.TextField(blank=True, max_length=2000, null=True, verbose_name='内容')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='首页头图(750×314)')),
                ('url', models.TextField(blank=True, max_length=500, null=True, verbose_name='详情链接')),
                ('begin_date', models.DateTimeField(verbose_name='开始日期')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='结束日期')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '活动宣传',
                'verbose_name_plural': '活动宣传',
                'db_table': 'event',
            },
        ),
    ]
