# Generated by Django 2.0.7 on 2019-08-01 18:39

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_body',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', max_length=2000, null=True, verbose_name='内容'),
        ),
    ]
