# Generated by Django 2.0.7 on 2019-05-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlatForm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointlog',
            name='img',
            field=models.ImageField(default='', upload_to='', verbose_name='相关截图'),
            preserve_default=False,
        ),
    ]
