# Generated by Django 2.0.7 on 2019-05-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlatForm', '0002_pointlog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointlog',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='相关截图'),
        ),
    ]
