# Generated by Django 2.0.7 on 2019-05-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlatForm', '0003_auto_20190504_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointlog',
            name='remark',
            field=models.TextField(default='', max_length=1000, verbose_name='管理员备注'),
            preserve_default=False,
        ),
    ]
