# Generated by Django 2.0.7 on 2019-05-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlatForm', '0004_pointlog_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointlog',
            name='remark',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='管理员备注'),
        ),
    ]
