# Generated by Django 2.0.7 on 2019-05-22 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0003_auto_20190522_1535'),
        ('PlatForm', '0005_auto_20190506_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prize_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='兑换奖品名称')),
                ('number', models.ImageField(upload_to='', verbose_name='兑换数量')),
                ('address', models.TextField(max_length=1000, verbose_name='地址信息')),
                ('date', models.DateTimeField(verbose_name='兑换日期')),
                ('express', models.CharField(blank=True, max_length=255, null=True, verbose_name='快递信息')),
                ('state', models.IntegerField(choices=[(0, '申请中'), (1, '已发货'), (2, '已完成'), (3, '已取消')], verbose_name='订单状态')),
                ('remark', models.TextField(blank=True, max_length=1000, null=True, verbose_name='备注信息')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='邮寄负责人')),
                ('prize_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlatForm.Prize', verbose_name='兑换奖品编号')),
                ('qq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Signon', verbose_name='兑换账号')),
            ],
            options={
                'verbose_name': '兑换订单',
                'verbose_name_plural': '兑换订单',
                'db_table': 'order',
            },
        ),
    ]
