# Generated by Django 2.0.7 on 2019-05-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlatForm', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(verbose_name='兑换数量'),
        ),
    ]
