# Generated by Django 2.0.7 on 2019-05-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlatForm', '0007_auto_20190522_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='point',
            field=models.IntegerField(default=100, verbose_name='兑换价格'),
            preserve_default=False,
        ),
    ]
