# Generated by Django 2.0.7 on 2019-05-23 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlatForm', '0008_prize_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prize',
            old_name='prize_id',
            new_name='prize_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prize_id',
        ),
        migrations.AddField(
            model_name='order',
            name='prize',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PlatForm.Prize', verbose_name='兑换奖品id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='邮寄负责人'),
        ),
    ]
