# Generated by Django 2.0.7 on 2019-05-23 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlatForm', '0009_auto_20190523_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='point',
            field=models.IntegerField(default=1, verbose_name='消耗贝化值'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='prize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PlatForm.Prize', verbose_name='兑换奖品id'),
        ),
    ]
