# Generated by Django 2.0.7 on 2019-06-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlatForm', '0010_auto_20190523_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='publish',
            field=models.IntegerField(choices=[(0, '隐藏'), (1, '公开'), (2, '仅作展示')], default=1, verbose_name='公开状态'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pointlog',
            name='operate_date',
            field=models.DateTimeField(verbose_name='操作日期'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片'),
        ),
    ]
