# Generated by Django 2.0.7 on 2019-07-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlatForm', '0011_auto_20190628_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointlog',
            name='state',
            field=models.IntegerField(choices=[(0, '登记待评'), (1, '有效'), (2, '作废'), (3, '其他')], default=1, verbose_name='状态'),
            preserve_default=False,
        ),
    ]
