# Generated by Django 2.0.7 on 2019-08-01 18:39

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlatForm', '0012_pointlog_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointlog',
            options={'verbose_name': '贝化值操作', 'verbose_name_plural': '贝化值操作'},
        ),
        migrations.AlterField(
            model_name='prize',
            name='description',
            field=DjangoUeditor.models.UEditorField(default='', max_length=2000, verbose_name='奖品描述'),
        ),
    ]
