# Generated by Django 2.0.7 on 2019-05-04 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qq', models.CharField(max_length=255, verbose_name='QQ号')),
                ('feedback_type', models.IntegerField(choices=[(0, '类型1'), (1, '类型2'), (2, '类型3'), (3, '类型4'), (4, '类型5')], verbose_name='反馈类型')),
                ('feedback_body', models.TextField(max_length=2000, verbose_name='反馈内容')),
                ('feedback_date', models.DateTimeField(verbose_name='反馈日期')),
            ],
            options={
                'verbose_name': '反馈信息',
                'verbose_name_plural': '反馈信息',
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notice_title', models.CharField(max_length=100, verbose_name='标题')),
                ('notice_body', models.TextField(max_length=2000, verbose_name='内容')),
                ('notice_date', models.DateTimeField(auto_now=True, null=True, verbose_name='发布日期')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Signon', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '消息通知',
                'verbose_name_plural': '消息通知',
                'db_table': 'notice',
            },
        ),
    ]
