# Generated by Django 2.0.7 on 2019-05-04 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MessageCenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
    ]
