# Generated by Django 2.0.7 on 2019-08-01 18:39

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageCenter', '0004_auto_20190525_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': '系统公告', 'verbose_name_plural': '系统公告'},
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_alt',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='预览(20字内加……)'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_body',
            field=DjangoUeditor.models.UEditorField(default='', max_length=2000, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_date',
            field=models.DateTimeField(verbose_name='发布日期'),
        ),
    ]
